<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="100">
</p>



# Curso Propedéutico en *Programación*

## Introducción a `python` resolviendo preguntas


**Julio Waissman Vilanova**



### Tipos

¿Cuales son los tipos de datos básicos? Revisa los tipos siguientes:

1. Tipos numéricos `int`, `float`, `complex`
2. Cadenas de caracteres
3. Tuplas
4. Listas
5. Diccionarios
6. Conjuntos

Da ejemplo de sobrecarga de operadores (en particular `+` y `*`)



In [1]:
x = (3, 4)
y = (1, 2)

z1 = tuple(x_elem + y_elem for x_elem, y_elem in zip(x, y))


z2 = tuple(x_elem * y_elem for x_elem, y_elem in zip(x, y))
print(z1, z2)

(4, 6) (3, 8)


¿Que significa que unos tipos sean *mutables* y otros *inmutables*?

Realiza un pequeño programa donde quede claro lo que significa que un tipo de datos sea mutable, e ilustra el uso del método `copy.deepcopy()`.

In [2]:
import copy

#Inmutable
x = 5
y = x + 1

#Mutable
lista_original = [1, 2, 3]
lista_copia = lista_original[:]
lista_original.append(4)

#Uso de copy.deepcopy()
lista_original = [1, 2, [3, 4]]
lista_copia_profunda = copy.deepcopy(lista_original)
lista_original[2].append(5)
lista_original

[1, 2, [3, 4, 5]]

### *Comprehension* de listas, conjuntos y diccionarios

Escribe, en una sola linea, una expresión que genere una lista con todos los números enteros que se encuentran entre $1$ y $n$
que sean divisibles por $3$ y $7$ y que el dígito menos significativo del número sea $6$.

In [3]:
n = 10_000

# Escribe aqui el *one linner*
numeros = [num for num in range(1, n+1) if num % 3 == 0 and num % 7 == 0 and num % 10 == 6]
numeros

[126,
 336,
 546,
 756,
 966,
 1176,
 1386,
 1596,
 1806,
 2016,
 2226,
 2436,
 2646,
 2856,
 3066,
 3276,
 3486,
 3696,
 3906,
 4116,
 4326,
 4536,
 4746,
 4956,
 5166,
 5376,
 5586,
 5796,
 6006,
 6216,
 6426,
 6636,
 6846,
 7056,
 7266,
 7476,
 7686,
 7896,
 8106,
 8316,
 8526,
 8736,
 8946,
 9156,
 9366,
 9576,
 9786,
 9996]

### Funciones

Escribe una función que:

1. reciba una lista de elementos (letras, números, lo que sea),
2. cuente la ocurrencia de cada elemento en la lista,
3. devuelva las ocurrencias en forma de diccionario,
4. si imprime es True, imprima un histograma de ocurrencias, por ejemplo:

```python

lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

d = funcion_ejemplo(lista, imprime = True)

1    		***** 	(5 -> 50%)
'a'  		***   	(3 -> 30%)
13		*	(1 -> 10%)
'hola'		*	(1 -> 10%)

```

In [4]:
# Escribe la función aquí
def funcion_ejemplo(lista, imprime=False):
    ocurrencias = {}
    for elemento in lista:
        ocurrencias[elemento] = ocurrencias.get(elemento, 0) + 1
    
    total_elementos = len(lista)
    porcentajes = {elemento: (ocurrencias[elemento] / total_elementos) * 100 for elemento in ocurrencias}
    
    if imprime:
        for elemento, conteo in ocurrencias.items():
            porcentaje = porcentajes[elemento]
            print(f"{elemento:<10} {'*' * conteo}  ({conteo} -> {porcentaje:.0f}%)")
    
    return ocurrencias

In [5]:
# Realiza pruebas aquí
lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]
d = funcion_ejemplo(lista, imprime = True)
print(d)

1          *****  (5 -> 50%)
a          ***  (3 -> 30%)
13         *  (1 -> 10%)
hola       *  (1 -> 10%)
{1: 5, 'a': 3, 13: 1, 'hola': 1}


Escribe una función que modifique un diccionario y regrese el diccionario modificado y una copia del original, donde cada entrada
del diccionario sea una lista de valores. Ten en cuenta que si una entrada del diccionario es de tipo mutable, al modificarlo en la
copia se modifica el original. Utiliza el modulo `copy` para evitar este problema. Ejemplo de la función:

```python
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
{'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}

print(dic2)
{'Pepe':[12, 'febrero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
```

In [6]:
# Escribe la función fundicos aquí
def fundicos(diccionario, clave, indice, valor):
    diccionario_copia = copy.deepcopy(diccionario)
    
    if clave in diccionario_copia:
        if isinstance(diccionario_copia[clave], list):
            diccionario_copia[clave][indice] = valor
    
    return diccionario_copia

In [7]:
# Realiza pruebas de fundicos aquí
dic1 = {'Pepe':[20, 'enero', 2002], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'noviembre')

print(dic1)
print(dic2)

{'Pepe': [20, 'enero', 2002], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}
{'Pepe': [20, 'noviembre', 2002], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}


### Generadores

Escribe un generador que reciba una lista y genere todas las permutaciones que se puedan hacer con los elementos de la lista

In [8]:
# Escribe aqui fun1

def permutaciones(lista):
    """
    Permutaciones de los elementos de una lista.

    Devuelve un generador con todas las permutaciones posibles de los elementos de la lista de entrada
    """
    # Caso base: si la lista tiene un solo elemento, devuelve una lista con ese elemento
    if len(lista) == 1:
        yield lista
    else:
        # Recorre cada elemento de la lista
        for i in range(len(lista)):
            # Genera todas las permutaciones de los elementos restantes
            for perm in permutaciones(lista[:i] + lista[i+1:]):
                # Combina el elemento actual con cada permutación de los elementos restantes
                yield [lista[i]] + perm

In [9]:
# Realiza pruebas de fun2 aquí
for p in permutaciones(['a', 'b', 'c', 'd']):
    print(p)

['a', 'b', 'c', 'd']
['a', 'b', 'd', 'c']
['a', 'c', 'b', 'd']
['a', 'c', 'd', 'b']
['a', 'd', 'b', 'c']
['a', 'd', 'c', 'b']
['b', 'a', 'c', 'd']
['b', 'a', 'd', 'c']
['b', 'c', 'a', 'd']
['b', 'c', 'd', 'a']
['b', 'd', 'a', 'c']
['b', 'd', 'c', 'a']
['c', 'a', 'b', 'd']
['c', 'a', 'd', 'b']
['c', 'b', 'a', 'd']
['c', 'b', 'd', 'a']
['c', 'd', 'a', 'b']
['c', 'd', 'b', 'a']
['d', 'a', 'b', 'c']
['d', 'a', 'c', 'b']
['d', 'b', 'a', 'c']
['d', 'b', 'c', 'a']
['d', 'c', 'a', 'b']
['d', 'c', 'b', 'a']


Ahora escribe una funcipn que reciba 4 digitos del 0 al 9, y devuelva una lista con todas las horas váidas que se puedan hacer con estos dígitos en forma de lista de strings con la forma `"HH:MM"`.

In [18]:
def horas_validas(lista):
    """
    Genera todas las horas válidas posibles a partir de una lista de dígitos del 0 al 9.

    Devuelve una lista de strings con la forma "HH:MM".
    """
    horas = []
    # Combinaciones posibles de los dígitos
    for h1 in lista:
        for h2 in lista:
            for m1 in lista:
                for m2 in lista:
                    hora = f"{h1}{h2}:{m1}{m2}"
                    # Verificar si la hora es válida
                    if int(hora[:2]) < 24 and int(hora[3:]) < 60:
                        horas.append(hora)

    return horas

Validando:

In [19]:
print(horas_validas([1,2,3,7]))

['11:11', '11:12', '11:13', '11:17', '11:21', '11:22', '11:23', '11:27', '11:31', '11:32', '11:33', '11:37', '12:11', '12:12', '12:13', '12:17', '12:21', '12:22', '12:23', '12:27', '12:31', '12:32', '12:33', '12:37', '13:11', '13:12', '13:13', '13:17', '13:21', '13:22', '13:23', '13:27', '13:31', '13:32', '13:33', '13:37', '17:11', '17:12', '17:13', '17:17', '17:21', '17:22', '17:23', '17:27', '17:31', '17:32', '17:33', '17:37', '21:11', '21:12', '21:13', '21:17', '21:21', '21:22', '21:23', '21:27', '21:31', '21:32', '21:33', '21:37', '22:11', '22:12', '22:13', '22:17', '22:21', '22:22', '22:23', '22:27', '22:31', '22:32', '22:33', '22:37', '23:11', '23:12', '23:13', '23:17', '23:21', '23:22', '23:23', '23:27', '23:31', '23:32', '23:33', '23:37']


Escribe una función, lo más compacta posible, que escoja entre los 3 patrones ascii a continuación, e imprima en pantalla
el deseado, pero de dimensión $n$ ($n \ge 4$), toma en cuanta que para algunos valores de $n$ habrá
algún(os) patrones que no se puedan hacer.

```
          *             ++++           oooooooo
          **            ++++           ooo  ooo
          ***           ++++           oo    oo
          ****          ++++           o      o
          *****             ++++       o      o
          ******            ++++       oo    oo
          *******           ++++       ooo  ooo
          ********          ++++       oooooooo

```

In [12]:
# Escribe aquí la función
def imprimir_patron(n):
    if n < 4:
        print("El valor de n debe ser mayor o igual a 4.")
        return
    
    if n % 2 == 0:
        patron = ["*"*i for i in range(1, n//2 + 1)]
        patron += patron[::-1]
    else:
        patron = ["*"*i for i in range(1, n//2 + 2)]
        patron += patron[-2::-1]
    
    for linea in patron:
        print(linea.center(n))

In [13]:
#Realiza pruebas aquí
# Ejemplo de uso
imprimir_patron(20)

         *          
         **         
        ***         
        ****        
       *****        
       ******       
      *******       
      ********      
     *********      
     **********     
     **********     
     *********      
      ********      
      *******       
       ******       
       *****        
        ****        
        ***         
         **         
         *          


### Clases y objetos

Diseña una clase Matriz con las siguientes características:

1. Como inicialización de un objeto es necesario conocer $n$, $m$ y tipo. En caso de no proporcionar $m$ la matriz se asume cuadrada de $n \times n$. En caso de no proporcionar $n$ la matriz tendrá una dimensión de $1 \times 1$.
2. De no especificarse todos los elementos se inicializan a 0, a menos que exista un tipo especial ( `unos` o `diag` por el momento).
3. Implementa con sobrecarga la suma de matrices, la multiplicación de matrices y la multiplicación por un escalar.
4. Implementa como métodos eliminar columna y eliminar fila.   
5. Programa la representación visual de la matriz.
6. Ten en cuenta tambien el manejo de errores.


Ejemplo de uso:

```
>>> A = Matriz(n=3, m=4)

>>> print(A)
0 0 0 0
0 0 0 0
0 0 0 0

>>> A = A.quitafila(2)

>>> print(A)
0 0 0 0
0 0 0 0

>>> B = Matriz(4,4,'diag')

>>> print(B)
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

>>> C = Matriz(4,1,'unos')

>>> print(C)
1
1
1
1

>>> D = 3 * B * C

>>> print(D)
3
3
3
3

>>> E = 3 * B + C
error "No seas menso, si no son de la misma dimensión las matrices no se pueden sumar"
```

In [14]:
# Desarrolla aqui la clase
import numpy as np

class Matriz:
    def __init__(self, n=1, m=None, tipo='ceros'):
        self.n = n
        self.m = m if m is not None else n
        self.tipo = tipo
        self.matriz = self._inicializar_matriz()

    def _inicializar_matriz(self):
        if self.tipo == 'ceros':
            return np.zeros((self.n, self.m))
        elif self.tipo == 'unos':
            return np.ones((self.n, self.m))
        elif self.tipo == 'diag':
            return np.eye(self.n, self.m)
        else:
            raise ValueError("Tipo de matriz no soportado. Use 'ceros', 'unos' o 'diag'.")

    def __repr__(self):
        return str(self.matriz)

    def __add__(self, other):
        if isinstance(other, Matriz):
            if self.matriz.shape != other.matriz.shape:
                raise ValueError("Las matrices deben tener la misma dimensión para sumarse.")
            return Matriz(n=self.n, m=self.m, tipo='ceros')._set_data(self.matriz + other.matriz)
        else:
            raise ValueError("Solo se pueden sumar objetos de tipo Matriz.")

    def __mul__(self, other):
        if isinstance(other, Matriz):
            if self.matriz.shape[1] != other.matriz.shape[0]:
                raise ValueError("Las matrices no tienen dimensiones compatibles para la multiplicación.")
            return Matriz(n=self.n, m=other.m, tipo='ceros')._set_data(np.dot(self.matriz, other.matriz))
        elif isinstance(other, (int, float)):
            return Matriz(n=self.n, m=self.m, tipo='ceros')._set_data(self.matriz * other)
        else:
            raise ValueError("La matriz solo puede ser multiplicada por otra matriz o un escalar (int o float).")

    def __rmul__(self, other):
        if isinstance(other, (int, float)):
            return self * other
        else:
            raise ValueError("La matriz solo puede ser multiplicada por un escalar (int o float).")

    def _set_data(self, data):
        self.matriz = data
        return self

    def eliminar_fila(self, fila):
        if fila < 0 or fila >= self.n:
            raise IndexError("El índice de fila está fuera del rango.")
        self.matriz = np.delete(self.matriz, fila, axis=0)
        self.n -= 1
        return self

    def eliminar_columna(self, columna):
        if columna < 0 or columna >= self.m:
            raise IndexError("El índice de columna está fuera del rango.")
        self.matriz = np.delete(self.matriz, columna, axis=1)
        self.m -= 1
        return self

In [15]:
# Realiza las pruebas a la clase aquí
A = Matriz(n=3, m=4)
print('A =', A)

A = A.eliminar_fila(2)
print('A = ', A)

B = Matriz(4, 4, 'diag')
print('B = ', B)

C = Matriz(4, 1, 'unos')
print('C =', C)

D = 3 * B * C
print('D = ', D)

# Expandiendo C para que tenga la misma dimensión que B antes de sumar
C_expandida = Matriz(4, 4, 'ceros')._set_data(np.tile(C.matriz, (1, 4)))
E = 3 * B + C_expandida
print('E = ', E)

A = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
A =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
B =  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
C = [[1.]
 [1.]
 [1.]
 [1.]]
D =  [[3.]
 [3.]
 [3.]
 [3.]]
E =  [[4. 1. 1. 1.]
 [1. 4. 1. 1.]
 [1. 1. 4. 1.]
 [1. 1. 1. 4.]]
